#!/usr/bin/env python3
# Generates gl_stub.cpp: every core OpenGL entry point a GL/gl.h declares,
# as an empty function.  For a Coin built with COIN_BUILD_GL_STUB (a host
# without any GL, such as a Python sandbox guest compiled to wasm): the
# library's direct gl*() calls resolve, and nothing ever renders.
#
#   python3 gen_gl_stub.py <path to GL/gl.h> > gl_stub.cpp
import re
import sys

decl = re.compile(r"^GLAPI\s+(.+?)\s*GLAPIENTRY\s+(gl\w+)\s*\((.*?)\)\s*;", re.S | re.M)
src = open(sys.argv[1]).read()
seen = set()
out = []
out.append("/* Generated by gen_gl_stub.py from %s -- do not edit.\n"
           " * The core OpenGL entry points as empty functions: a Coin built with\n"
           " * COIN_BUILD_GL_STUB links on a host that has no GL at all and never\n"
           " * renders (FreeCAD's sandbox guest, docs/Sandbox.md 7.10). */\n" % sys.argv[1].split("/")[-1])
out.append("#include <Inventor/system/gl.h>\n#include <cstring>\n")
out.append("extern \"C\" {\n")
vendor = re.compile(r"(MESA|EXT|ARB|NV|ATI|SGIS|SGIX|SGI|IBM|SUN|APPLE|INTEL|OES|3DFX|PGI|HP|WIN)$")
for ret, name, args in decl.findall(src):
    # core entry points only: the vendor extensions are behind #ifdefs,
    # their types with them, and Coin reaches extensions through its glue
    if name in seen or vendor.search(name) or "(" in args:
        continue
    seen.add(name)
    ret = " ".join(ret.split())
    args = " ".join(args.split())
    if args in ("", "void"):
        args = "void"
    body = ""
    if name == "glGetString":
        body = ("    switch (name) {\n"
                "    case GL_VERSION: return (const GLubyte *)\"1.1 stub\";\n"
                "    case GL_VENDOR: return (const GLubyte *)\"none\";\n"
                "    case GL_RENDERER: return (const GLubyte *)\"Coin GL stub\";\n"
                "    default: return (const GLubyte *)\"\";\n"
                "    }\n")
    elif name in ("glGetIntegerv", "glGetFloatv", "glGetDoublev", "glGetBooleanv"):
        body = "    (void)pname;\n    if (params) params[0] = 0;\n"
    elif ret != "void":
        body = "    return 0;\n"
    # silence unused-parameter warnings by casting each named parameter
    if body == "" or body.startswith("    return 0"):
        names = []
        if args != "void":
            for a in args.split(","):
                a = re.sub(r"\[\s*\d*\s*\]\s*$", "", a.strip()).strip()
                m = re.search(r"(\w+)$", a)
                if m and m.group(1) not in ("void", "const"):
                    names.append(m.group(1))
        casts = "".join("    (void)%s;\n" % n for n in names)
        body = casts + body
    out.append("%s %s(%s)\n{\n%s}\n" % (ret, name, args, body))
out.append("}  /* extern \"C\" */\n")
sys.stdout.write("\n".join(out))
