/* Generated by gen_gl_stub.py from gl.h -- do not edit.
 * The core OpenGL entry points as empty functions: a Coin built with
 * COIN_BUILD_GL_STUB links on a host that has no GL at all and never
 * renders (FreeCAD's sandbox guest, docs/Sandbox.md 7.10). */

#include <Inventor/system/gl.h>
#include <cstring>

extern "C" {

void glClearIndex(GLfloat c)
{
    (void)c;
}

void glClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void glClear(GLbitfield mask)
{
    (void)mask;
}

void glIndexMask(GLuint mask)
{
    (void)mask;
}

void glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void glAlphaFunc(GLenum func, GLclampf ref)
{
    (void)func;
    (void)ref;
}

void glBlendFunc(GLenum sfactor, GLenum dfactor)
{
    (void)sfactor;
    (void)dfactor;
}

void glLogicOp(GLenum opcode)
{
    (void)opcode;
}

void glCullFace(GLenum mode)
{
    (void)mode;
}

void glFrontFace(GLenum mode)
{
    (void)mode;
}

void glPointSize(GLfloat size)
{
    (void)size;
}

void glLineWidth(GLfloat width)
{
    (void)width;
}

void glLineStipple(GLint factor, GLushort pattern)
{
    (void)factor;
    (void)pattern;
}

void glPolygonMode(GLenum face, GLenum mode)
{
    (void)face;
    (void)mode;
}

void glPolygonOffset(GLfloat factor, GLfloat units)
{
    (void)factor;
    (void)units;
}

void glPolygonStipple(const GLubyte *mask)
{
    (void)mask;
}

void glGetPolygonStipple(GLubyte *mask)
{
    (void)mask;
}

void glEdgeFlag(GLboolean flag)
{
    (void)flag;
}

void glEdgeFlagv(const GLboolean *flag)
{
    (void)flag;
}

void glScissor(GLint x, GLint y, GLsizei width, GLsizei height)
{
    (void)x;
    (void)y;
    (void)width;
    (void)height;
}

void glClipPlane(GLenum plane, const GLdouble *equation)
{
    (void)plane;
    (void)equation;
}

void glGetClipPlane(GLenum plane, GLdouble *equation)
{
    (void)plane;
    (void)equation;
}

void glDrawBuffer(GLenum mode)
{
    (void)mode;
}

void glReadBuffer(GLenum mode)
{
    (void)mode;
}

void glEnable(GLenum cap)
{
    (void)cap;
}

void glDisable(GLenum cap)
{
    (void)cap;
}

GLboolean glIsEnabled(GLenum cap)
{
    (void)cap;
    return 0;
}

void glEnableClientState(GLenum cap)
{
    (void)cap;
}

void glDisableClientState(GLenum cap)
{
    (void)cap;
}

void glGetBooleanv(GLenum pname, GLboolean *params)
{
    (void)pname;
    if (params) params[0] = 0;
}

void glGetDoublev(GLenum pname, GLdouble *params)
{
    (void)pname;
    if (params) params[0] = 0;
}

void glGetFloatv(GLenum pname, GLfloat *params)
{
    (void)pname;
    if (params) params[0] = 0;
}

void glGetIntegerv(GLenum pname, GLint *params)
{
    (void)pname;
    if (params) params[0] = 0;
}

void glPushAttrib(GLbitfield mask)
{
    (void)mask;
}

void glPopAttrib(void)
{
}

void glPushClientAttrib(GLbitfield mask)
{
    (void)mask;
}

void glPopClientAttrib(void)
{
}

GLint glRenderMode(GLenum mode)
{
    (void)mode;
    return 0;
}

GLenum glGetError(void)
{
    return 0;
}

const GLubyte * glGetString(GLenum name)
{
    switch (name) {
    case GL_VERSION: return (const GLubyte *)"1.1 stub";
    case GL_VENDOR: return (const GLubyte *)"none";
    case GL_RENDERER: return (const GLubyte *)"Coin GL stub";
    default: return (const GLubyte *)"";
    }
}

void glFinish(void)
{
}

void glFlush(void)
{
}

void glHint(GLenum target, GLenum mode)
{
    (void)target;
    (void)mode;
}

void glClearDepth(GLclampd depth)
{
    (void)depth;
}

void glDepthFunc(GLenum func)
{
    (void)func;
}

void glDepthMask(GLboolean flag)
{
    (void)flag;
}

void glDepthRange(GLclampd near_val, GLclampd far_val)
{
    (void)near_val;
    (void)far_val;
}

void glClearAccum(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void glAccum(GLenum op, GLfloat value)
{
    (void)op;
    (void)value;
}

void glMatrixMode(GLenum mode)
{
    (void)mode;
}

void glOrtho(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val)
{
    (void)left;
    (void)right;
    (void)bottom;
    (void)top;
    (void)near_val;
    (void)far_val;
}

void glFrustum(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val)
{
    (void)left;
    (void)right;
    (void)bottom;
    (void)top;
    (void)near_val;
    (void)far_val;
}

void glViewport(GLint x, GLint y, GLsizei width, GLsizei height)
{
    (void)x;
    (void)y;
    (void)width;
    (void)height;
}

void glPushMatrix(void)
{
}

void glPopMatrix(void)
{
}

void glLoadIdentity(void)
{
}

void glLoadMatrixd(const GLdouble *m)
{
    (void)m;
}

void glLoadMatrixf(const GLfloat *m)
{
    (void)m;
}

void glMultMatrixd(const GLdouble *m)
{
    (void)m;
}

void glMultMatrixf(const GLfloat *m)
{
    (void)m;
}

void glRotated(GLdouble angle, GLdouble x, GLdouble y, GLdouble z)
{
    (void)angle;
    (void)x;
    (void)y;
    (void)z;
}

void glRotatef(GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
{
    (void)angle;
    (void)x;
    (void)y;
    (void)z;
}

void glScaled(GLdouble x, GLdouble y, GLdouble z)
{
    (void)x;
    (void)y;
    (void)z;
}

void glScalef(GLfloat x, GLfloat y, GLfloat z)
{
    (void)x;
    (void)y;
    (void)z;
}

void glTranslated(GLdouble x, GLdouble y, GLdouble z)
{
    (void)x;
    (void)y;
    (void)z;
}

void glTranslatef(GLfloat x, GLfloat y, GLfloat z)
{
    (void)x;
    (void)y;
    (void)z;
}

GLboolean glIsList(GLuint list)
{
    (void)list;
    return 0;
}

void glDeleteLists(GLuint list, GLsizei range)
{
    (void)list;
    (void)range;
}

GLuint glGenLists(GLsizei range)
{
    (void)range;
    return 0;
}

void glNewList(GLuint list, GLenum mode)
{
    (void)list;
    (void)mode;
}

void glEndList(void)
{
}

void glCallList(GLuint list)
{
    (void)list;
}

void glCallLists(GLsizei n, GLenum type, const GLvoid *lists)
{
    (void)n;
    (void)type;
    (void)lists;
}

void glListBase(GLuint base)
{
    (void)base;
}

void glBegin(GLenum mode)
{
    (void)mode;
}

void glEnd(void)
{
}

void glVertex2d(GLdouble x, GLdouble y)
{
    (void)x;
    (void)y;
}

void glVertex2f(GLfloat x, GLfloat y)
{
    (void)x;
    (void)y;
}

void glVertex2i(GLint x, GLint y)
{
    (void)x;
    (void)y;
}

void glVertex2s(GLshort x, GLshort y)
{
    (void)x;
    (void)y;
}

void glVertex3d(GLdouble x, GLdouble y, GLdouble z)
{
    (void)x;
    (void)y;
    (void)z;
}

void glVertex3f(GLfloat x, GLfloat y, GLfloat z)
{
    (void)x;
    (void)y;
    (void)z;
}

void glVertex3i(GLint x, GLint y, GLint z)
{
    (void)x;
    (void)y;
    (void)z;
}

void glVertex3s(GLshort x, GLshort y, GLshort z)
{
    (void)x;
    (void)y;
    (void)z;
}

void glVertex4d(GLdouble x, GLdouble y, GLdouble z, GLdouble w)
{
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}

void glVertex4f(GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}

void glVertex4i(GLint x, GLint y, GLint z, GLint w)
{
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}

void glVertex4s(GLshort x, GLshort y, GLshort z, GLshort w)
{
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}

void glVertex2dv(const GLdouble *v)
{
    (void)v;
}

void glVertex2fv(const GLfloat *v)
{
    (void)v;
}

void glVertex2iv(const GLint *v)
{
    (void)v;
}

void glVertex2sv(const GLshort *v)
{
    (void)v;
}

void glVertex3dv(const GLdouble *v)
{
    (void)v;
}

void glVertex3fv(const GLfloat *v)
{
    (void)v;
}

void glVertex3iv(const GLint *v)
{
    (void)v;
}

void glVertex3sv(const GLshort *v)
{
    (void)v;
}

void glVertex4dv(const GLdouble *v)
{
    (void)v;
}

void glVertex4fv(const GLfloat *v)
{
    (void)v;
}

void glVertex4iv(const GLint *v)
{
    (void)v;
}

void glVertex4sv(const GLshort *v)
{
    (void)v;
}

void glNormal3b(GLbyte nx, GLbyte ny, GLbyte nz)
{
    (void)nx;
    (void)ny;
    (void)nz;
}

void glNormal3d(GLdouble nx, GLdouble ny, GLdouble nz)
{
    (void)nx;
    (void)ny;
    (void)nz;
}

void glNormal3f(GLfloat nx, GLfloat ny, GLfloat nz)
{
    (void)nx;
    (void)ny;
    (void)nz;
}

void glNormal3i(GLint nx, GLint ny, GLint nz)
{
    (void)nx;
    (void)ny;
    (void)nz;
}

void glNormal3s(GLshort nx, GLshort ny, GLshort nz)
{
    (void)nx;
    (void)ny;
    (void)nz;
}

void glNormal3bv(const GLbyte *v)
{
    (void)v;
}

void glNormal3dv(const GLdouble *v)
{
    (void)v;
}

void glNormal3fv(const GLfloat *v)
{
    (void)v;
}

void glNormal3iv(const GLint *v)
{
    (void)v;
}

void glNormal3sv(const GLshort *v)
{
    (void)v;
}

void glIndexd(GLdouble c)
{
    (void)c;
}

void glIndexf(GLfloat c)
{
    (void)c;
}

void glIndexi(GLint c)
{
    (void)c;
}

void glIndexs(GLshort c)
{
    (void)c;
}

void glIndexub(GLubyte c)
{
    (void)c;
}

void glIndexdv(const GLdouble *c)
{
    (void)c;
}

void glIndexfv(const GLfloat *c)
{
    (void)c;
}

void glIndexiv(const GLint *c)
{
    (void)c;
}

void glIndexsv(const GLshort *c)
{
    (void)c;
}

void glIndexubv(const GLubyte *c)
{
    (void)c;
}

void glColor3b(GLbyte red, GLbyte green, GLbyte blue)
{
    (void)red;
    (void)green;
    (void)blue;
}

void glColor3d(GLdouble red, GLdouble green, GLdouble blue)
{
    (void)red;
    (void)green;
    (void)blue;
}

void glColor3f(GLfloat red, GLfloat green, GLfloat blue)
{
    (void)red;
    (void)green;
    (void)blue;
}

void glColor3i(GLint red, GLint green, GLint blue)
{
    (void)red;
    (void)green;
    (void)blue;
}

void glColor3s(GLshort red, GLshort green, GLshort blue)
{
    (void)red;
    (void)green;
    (void)blue;
}

void glColor3ub(GLubyte red, GLubyte green, GLubyte blue)
{
    (void)red;
    (void)green;
    (void)blue;
}

void glColor3ui(GLuint red, GLuint green, GLuint blue)
{
    (void)red;
    (void)green;
    (void)blue;
}

void glColor3us(GLushort red, GLushort green, GLushort blue)
{
    (void)red;
    (void)green;
    (void)blue;
}

void glColor4b(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void glColor4d(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void glColor4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void glColor4i(GLint red, GLint green, GLint blue, GLint alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void glColor4s(GLshort red, GLshort green, GLshort blue, GLshort alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void glColor4ub(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void glColor4ui(GLuint red, GLuint green, GLuint blue, GLuint alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void glColor4us(GLushort red, GLushort green, GLushort blue, GLushort alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void glColor3bv(const GLbyte *v)
{
    (void)v;
}

void glColor3dv(const GLdouble *v)
{
    (void)v;
}

void glColor3fv(const GLfloat *v)
{
    (void)v;
}

void glColor3iv(const GLint *v)
{
    (void)v;
}

void glColor3sv(const GLshort *v)
{
    (void)v;
}

void glColor3ubv(const GLubyte *v)
{
    (void)v;
}

void glColor3uiv(const GLuint *v)
{
    (void)v;
}

void glColor3usv(const GLushort *v)
{
    (void)v;
}

void glColor4bv(const GLbyte *v)
{
    (void)v;
}

void glColor4dv(const GLdouble *v)
{
    (void)v;
}

void glColor4fv(const GLfloat *v)
{
    (void)v;
}

void glColor4iv(const GLint *v)
{
    (void)v;
}

void glColor4sv(const GLshort *v)
{
    (void)v;
}

void glColor4ubv(const GLubyte *v)
{
    (void)v;
}

void glColor4uiv(const GLuint *v)
{
    (void)v;
}

void glColor4usv(const GLushort *v)
{
    (void)v;
}

void glTexCoord1d(GLdouble s)
{
    (void)s;
}

void glTexCoord1f(GLfloat s)
{
    (void)s;
}

void glTexCoord1i(GLint s)
{
    (void)s;
}

void glTexCoord1s(GLshort s)
{
    (void)s;
}

void glTexCoord2d(GLdouble s, GLdouble t)
{
    (void)s;
    (void)t;
}

void glTexCoord2f(GLfloat s, GLfloat t)
{
    (void)s;
    (void)t;
}

void glTexCoord2i(GLint s, GLint t)
{
    (void)s;
    (void)t;
}

void glTexCoord2s(GLshort s, GLshort t)
{
    (void)s;
    (void)t;
}

void glTexCoord3d(GLdouble s, GLdouble t, GLdouble r)
{
    (void)s;
    (void)t;
    (void)r;
}

void glTexCoord3f(GLfloat s, GLfloat t, GLfloat r)
{
    (void)s;
    (void)t;
    (void)r;
}

void glTexCoord3i(GLint s, GLint t, GLint r)
{
    (void)s;
    (void)t;
    (void)r;
}

void glTexCoord3s(GLshort s, GLshort t, GLshort r)
{
    (void)s;
    (void)t;
    (void)r;
}

void glTexCoord4d(GLdouble s, GLdouble t, GLdouble r, GLdouble q)
{
    (void)s;
    (void)t;
    (void)r;
    (void)q;
}

void glTexCoord4f(GLfloat s, GLfloat t, GLfloat r, GLfloat q)
{
    (void)s;
    (void)t;
    (void)r;
    (void)q;
}

void glTexCoord4i(GLint s, GLint t, GLint r, GLint q)
{
    (void)s;
    (void)t;
    (void)r;
    (void)q;
}

void glTexCoord4s(GLshort s, GLshort t, GLshort r, GLshort q)
{
    (void)s;
    (void)t;
    (void)r;
    (void)q;
}

void glTexCoord1dv(const GLdouble *v)
{
    (void)v;
}

void glTexCoord1fv(const GLfloat *v)
{
    (void)v;
}

void glTexCoord1iv(const GLint *v)
{
    (void)v;
}

void glTexCoord1sv(const GLshort *v)
{
    (void)v;
}

void glTexCoord2dv(const GLdouble *v)
{
    (void)v;
}

void glTexCoord2fv(const GLfloat *v)
{
    (void)v;
}

void glTexCoord2iv(const GLint *v)
{
    (void)v;
}

void glTexCoord2sv(const GLshort *v)
{
    (void)v;
}

void glTexCoord3dv(const GLdouble *v)
{
    (void)v;
}

void glTexCoord3fv(const GLfloat *v)
{
    (void)v;
}

void glTexCoord3iv(const GLint *v)
{
    (void)v;
}

void glTexCoord3sv(const GLshort *v)
{
    (void)v;
}

void glTexCoord4dv(const GLdouble *v)
{
    (void)v;
}

void glTexCoord4fv(const GLfloat *v)
{
    (void)v;
}

void glTexCoord4iv(const GLint *v)
{
    (void)v;
}

void glTexCoord4sv(const GLshort *v)
{
    (void)v;
}

void glRasterPos2d(GLdouble x, GLdouble y)
{
    (void)x;
    (void)y;
}

void glRasterPos2f(GLfloat x, GLfloat y)
{
    (void)x;
    (void)y;
}

void glRasterPos2i(GLint x, GLint y)
{
    (void)x;
    (void)y;
}

void glRasterPos2s(GLshort x, GLshort y)
{
    (void)x;
    (void)y;
}

void glRasterPos3d(GLdouble x, GLdouble y, GLdouble z)
{
    (void)x;
    (void)y;
    (void)z;
}

void glRasterPos3f(GLfloat x, GLfloat y, GLfloat z)
{
    (void)x;
    (void)y;
    (void)z;
}

void glRasterPos3i(GLint x, GLint y, GLint z)
{
    (void)x;
    (void)y;
    (void)z;
}

void glRasterPos3s(GLshort x, GLshort y, GLshort z)
{
    (void)x;
    (void)y;
    (void)z;
}

void glRasterPos4d(GLdouble x, GLdouble y, GLdouble z, GLdouble w)
{
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}

void glRasterPos4f(GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}

void glRasterPos4i(GLint x, GLint y, GLint z, GLint w)
{
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}

void glRasterPos4s(GLshort x, GLshort y, GLshort z, GLshort w)
{
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}

void glRasterPos2dv(const GLdouble *v)
{
    (void)v;
}

void glRasterPos2fv(const GLfloat *v)
{
    (void)v;
}

void glRasterPos2iv(const GLint *v)
{
    (void)v;
}

void glRasterPos2sv(const GLshort *v)
{
    (void)v;
}

void glRasterPos3dv(const GLdouble *v)
{
    (void)v;
}

void glRasterPos3fv(const GLfloat *v)
{
    (void)v;
}

void glRasterPos3iv(const GLint *v)
{
    (void)v;
}

void glRasterPos3sv(const GLshort *v)
{
    (void)v;
}

void glRasterPos4dv(const GLdouble *v)
{
    (void)v;
}

void glRasterPos4fv(const GLfloat *v)
{
    (void)v;
}

void glRasterPos4iv(const GLint *v)
{
    (void)v;
}

void glRasterPos4sv(const GLshort *v)
{
    (void)v;
}

void glRectd(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2)
{
    (void)x1;
    (void)y1;
    (void)x2;
    (void)y2;
}

void glRectf(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2)
{
    (void)x1;
    (void)y1;
    (void)x2;
    (void)y2;
}

void glRecti(GLint x1, GLint y1, GLint x2, GLint y2)
{
    (void)x1;
    (void)y1;
    (void)x2;
    (void)y2;
}

void glRects(GLshort x1, GLshort y1, GLshort x2, GLshort y2)
{
    (void)x1;
    (void)y1;
    (void)x2;
    (void)y2;
}

void glRectdv(const GLdouble *v1, const GLdouble *v2)
{
    (void)v1;
    (void)v2;
}

void glRectfv(const GLfloat *v1, const GLfloat *v2)
{
    (void)v1;
    (void)v2;
}

void glRectiv(const GLint *v1, const GLint *v2)
{
    (void)v1;
    (void)v2;
}

void glRectsv(const GLshort *v1, const GLshort *v2)
{
    (void)v1;
    (void)v2;
}

void glVertexPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
{
    (void)size;
    (void)type;
    (void)stride;
    (void)ptr;
}

void glNormalPointer(GLenum type, GLsizei stride, const GLvoid *ptr)
{
    (void)type;
    (void)stride;
    (void)ptr;
}

void glColorPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
{
    (void)size;
    (void)type;
    (void)stride;
    (void)ptr;
}

void glIndexPointer(GLenum type, GLsizei stride, const GLvoid *ptr)
{
    (void)type;
    (void)stride;
    (void)ptr;
}

void glTexCoordPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
{
    (void)size;
    (void)type;
    (void)stride;
    (void)ptr;
}

void glEdgeFlagPointer(GLsizei stride, const GLvoid *ptr)
{
    (void)stride;
    (void)ptr;
}

void glGetPointerv(GLenum pname, GLvoid **params)
{
    (void)pname;
    (void)params;
}

void glArrayElement(GLint i)
{
    (void)i;
}

void glDrawArrays(GLenum mode, GLint first, GLsizei count)
{
    (void)mode;
    (void)first;
    (void)count;
}

void glDrawElements(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
{
    (void)mode;
    (void)count;
    (void)type;
    (void)indices;
}

void glInterleavedArrays(GLenum format, GLsizei stride, const GLvoid *pointer)
{
    (void)format;
    (void)stride;
    (void)pointer;
}

void glShadeModel(GLenum mode)
{
    (void)mode;
}

void glLightf(GLenum light, GLenum pname, GLfloat param)
{
    (void)light;
    (void)pname;
    (void)param;
}

void glLighti(GLenum light, GLenum pname, GLint param)
{
    (void)light;
    (void)pname;
    (void)param;
}

void glLightfv(GLenum light, GLenum pname, const GLfloat *params)
{
    (void)light;
    (void)pname;
    (void)params;
}

void glLightiv(GLenum light, GLenum pname, const GLint *params)
{
    (void)light;
    (void)pname;
    (void)params;
}

void glGetLightfv(GLenum light, GLenum pname, GLfloat *params)
{
    (void)light;
    (void)pname;
    (void)params;
}

void glGetLightiv(GLenum light, GLenum pname, GLint *params)
{
    (void)light;
    (void)pname;
    (void)params;
}

void glLightModelf(GLenum pname, GLfloat param)
{
    (void)pname;
    (void)param;
}

void glLightModeli(GLenum pname, GLint param)
{
    (void)pname;
    (void)param;
}

void glLightModelfv(GLenum pname, const GLfloat *params)
{
    (void)pname;
    (void)params;
}

void glLightModeliv(GLenum pname, const GLint *params)
{
    (void)pname;
    (void)params;
}

void glMaterialf(GLenum face, GLenum pname, GLfloat param)
{
    (void)face;
    (void)pname;
    (void)param;
}

void glMateriali(GLenum face, GLenum pname, GLint param)
{
    (void)face;
    (void)pname;
    (void)param;
}

void glMaterialfv(GLenum face, GLenum pname, const GLfloat *params)
{
    (void)face;
    (void)pname;
    (void)params;
}

void glMaterialiv(GLenum face, GLenum pname, const GLint *params)
{
    (void)face;
    (void)pname;
    (void)params;
}

void glGetMaterialfv(GLenum face, GLenum pname, GLfloat *params)
{
    (void)face;
    (void)pname;
    (void)params;
}

void glGetMaterialiv(GLenum face, GLenum pname, GLint *params)
{
    (void)face;
    (void)pname;
    (void)params;
}

void glColorMaterial(GLenum face, GLenum mode)
{
    (void)face;
    (void)mode;
}

void glPixelZoom(GLfloat xfactor, GLfloat yfactor)
{
    (void)xfactor;
    (void)yfactor;
}

void glPixelStoref(GLenum pname, GLfloat param)
{
    (void)pname;
    (void)param;
}

void glPixelStorei(GLenum pname, GLint param)
{
    (void)pname;
    (void)param;
}

void glPixelTransferf(GLenum pname, GLfloat param)
{
    (void)pname;
    (void)param;
}

void glPixelTransferi(GLenum pname, GLint param)
{
    (void)pname;
    (void)param;
}

void glPixelMapfv(GLenum map, GLsizei mapsize, const GLfloat *values)
{
    (void)map;
    (void)mapsize;
    (void)values;
}

void glPixelMapuiv(GLenum map, GLsizei mapsize, const GLuint *values)
{
    (void)map;
    (void)mapsize;
    (void)values;
}

void glPixelMapusv(GLenum map, GLsizei mapsize, const GLushort *values)
{
    (void)map;
    (void)mapsize;
    (void)values;
}

void glGetPixelMapfv(GLenum map, GLfloat *values)
{
    (void)map;
    (void)values;
}

void glGetPixelMapuiv(GLenum map, GLuint *values)
{
    (void)map;
    (void)values;
}

void glGetPixelMapusv(GLenum map, GLushort *values)
{
    (void)map;
    (void)values;
}

void glBitmap(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap)
{
    (void)width;
    (void)height;
    (void)xorig;
    (void)yorig;
    (void)xmove;
    (void)ymove;
    (void)bitmap;
}

void glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels)
{
    (void)x;
    (void)y;
    (void)width;
    (void)height;
    (void)format;
    (void)type;
    (void)pixels;
}

void glDrawPixels(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
{
    (void)width;
    (void)height;
    (void)format;
    (void)type;
    (void)pixels;
}

void glCopyPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type)
{
    (void)x;
    (void)y;
    (void)width;
    (void)height;
    (void)type;
}

void glStencilFunc(GLenum func, GLint ref, GLuint mask)
{
    (void)func;
    (void)ref;
    (void)mask;
}

void glStencilMask(GLuint mask)
{
    (void)mask;
}

void glStencilOp(GLenum fail, GLenum zfail, GLenum zpass)
{
    (void)fail;
    (void)zfail;
    (void)zpass;
}

void glClearStencil(GLint s)
{
    (void)s;
}

void glTexGend(GLenum coord, GLenum pname, GLdouble param)
{
    (void)coord;
    (void)pname;
    (void)param;
}

void glTexGenf(GLenum coord, GLenum pname, GLfloat param)
{
    (void)coord;
    (void)pname;
    (void)param;
}

void glTexGeni(GLenum coord, GLenum pname, GLint param)
{
    (void)coord;
    (void)pname;
    (void)param;
}

void glTexGendv(GLenum coord, GLenum pname, const GLdouble *params)
{
    (void)coord;
    (void)pname;
    (void)params;
}

void glTexGenfv(GLenum coord, GLenum pname, const GLfloat *params)
{
    (void)coord;
    (void)pname;
    (void)params;
}

void glTexGeniv(GLenum coord, GLenum pname, const GLint *params)
{
    (void)coord;
    (void)pname;
    (void)params;
}

void glGetTexGendv(GLenum coord, GLenum pname, GLdouble *params)
{
    (void)coord;
    (void)pname;
    (void)params;
}

void glGetTexGenfv(GLenum coord, GLenum pname, GLfloat *params)
{
    (void)coord;
    (void)pname;
    (void)params;
}

void glGetTexGeniv(GLenum coord, GLenum pname, GLint *params)
{
    (void)coord;
    (void)pname;
    (void)params;
}

void glTexEnvf(GLenum target, GLenum pname, GLfloat param)
{
    (void)target;
    (void)pname;
    (void)param;
}

void glTexEnvi(GLenum target, GLenum pname, GLint param)
{
    (void)target;
    (void)pname;
    (void)param;
}

void glTexEnvfv(GLenum target, GLenum pname, const GLfloat *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glTexEnviv(GLenum target, GLenum pname, const GLint *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glGetTexEnvfv(GLenum target, GLenum pname, GLfloat *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glGetTexEnviv(GLenum target, GLenum pname, GLint *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glTexParameterf(GLenum target, GLenum pname, GLfloat param)
{
    (void)target;
    (void)pname;
    (void)param;
}

void glTexParameteri(GLenum target, GLenum pname, GLint param)
{
    (void)target;
    (void)pname;
    (void)param;
}

void glTexParameterfv(GLenum target, GLenum pname, const GLfloat *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glTexParameteriv(GLenum target, GLenum pname, const GLint *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glGetTexParameterfv(GLenum target, GLenum pname, GLfloat *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glGetTexParameteriv(GLenum target, GLenum pname, GLint *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glGetTexLevelParameterfv(GLenum target, GLint level, GLenum pname, GLfloat *params)
{
    (void)target;
    (void)level;
    (void)pname;
    (void)params;
}

void glGetTexLevelParameteriv(GLenum target, GLint level, GLenum pname, GLint *params)
{
    (void)target;
    (void)level;
    (void)pname;
    (void)params;
}

void glTexImage1D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
{
    (void)target;
    (void)level;
    (void)internalFormat;
    (void)width;
    (void)border;
    (void)format;
    (void)type;
    (void)pixels;
}

void glTexImage2D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
{
    (void)target;
    (void)level;
    (void)internalFormat;
    (void)width;
    (void)height;
    (void)border;
    (void)format;
    (void)type;
    (void)pixels;
}

void glGetTexImage(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels)
{
    (void)target;
    (void)level;
    (void)format;
    (void)type;
    (void)pixels;
}

void glGenTextures(GLsizei n, GLuint *textures)
{
    (void)n;
    (void)textures;
}

void glDeleteTextures(GLsizei n, const GLuint *textures)
{
    (void)n;
    (void)textures;
}

void glBindTexture(GLenum target, GLuint texture)
{
    (void)target;
    (void)texture;
}

void glPrioritizeTextures(GLsizei n, const GLuint *textures, const GLclampf *priorities)
{
    (void)n;
    (void)textures;
    (void)priorities;
}

GLboolean glAreTexturesResident(GLsizei n, const GLuint *textures, GLboolean *residences)
{
    (void)n;
    (void)textures;
    (void)residences;
    return 0;
}

GLboolean glIsTexture(GLuint texture)
{
    (void)texture;
    return 0;
}

void glTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels)
{
    (void)target;
    (void)level;
    (void)xoffset;
    (void)width;
    (void)format;
    (void)type;
    (void)pixels;
}

void glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
{
    (void)target;
    (void)level;
    (void)xoffset;
    (void)yoffset;
    (void)width;
    (void)height;
    (void)format;
    (void)type;
    (void)pixels;
}

void glCopyTexImage1D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border)
{
    (void)target;
    (void)level;
    (void)internalformat;
    (void)x;
    (void)y;
    (void)width;
    (void)border;
}

void glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
{
    (void)target;
    (void)level;
    (void)internalformat;
    (void)x;
    (void)y;
    (void)width;
    (void)height;
    (void)border;
}

void glCopyTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
{
    (void)target;
    (void)level;
    (void)xoffset;
    (void)x;
    (void)y;
    (void)width;
}

void glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
    (void)target;
    (void)level;
    (void)xoffset;
    (void)yoffset;
    (void)x;
    (void)y;
    (void)width;
    (void)height;
}

void glMap1d(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points)
{
    (void)target;
    (void)u1;
    (void)u2;
    (void)stride;
    (void)order;
    (void)points;
}

void glMap1f(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points)
{
    (void)target;
    (void)u1;
    (void)u2;
    (void)stride;
    (void)order;
    (void)points;
}

void glMap2d(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points)
{
    (void)target;
    (void)u1;
    (void)u2;
    (void)ustride;
    (void)uorder;
    (void)v1;
    (void)v2;
    (void)vstride;
    (void)vorder;
    (void)points;
}

void glMap2f(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points)
{
    (void)target;
    (void)u1;
    (void)u2;
    (void)ustride;
    (void)uorder;
    (void)v1;
    (void)v2;
    (void)vstride;
    (void)vorder;
    (void)points;
}

void glGetMapdv(GLenum target, GLenum query, GLdouble *v)
{
    (void)target;
    (void)query;
    (void)v;
}

void glGetMapfv(GLenum target, GLenum query, GLfloat *v)
{
    (void)target;
    (void)query;
    (void)v;
}

void glGetMapiv(GLenum target, GLenum query, GLint *v)
{
    (void)target;
    (void)query;
    (void)v;
}

void glEvalCoord1d(GLdouble u)
{
    (void)u;
}

void glEvalCoord1f(GLfloat u)
{
    (void)u;
}

void glEvalCoord1dv(const GLdouble *u)
{
    (void)u;
}

void glEvalCoord1fv(const GLfloat *u)
{
    (void)u;
}

void glEvalCoord2d(GLdouble u, GLdouble v)
{
    (void)u;
    (void)v;
}

void glEvalCoord2f(GLfloat u, GLfloat v)
{
    (void)u;
    (void)v;
}

void glEvalCoord2dv(const GLdouble *u)
{
    (void)u;
}

void glEvalCoord2fv(const GLfloat *u)
{
    (void)u;
}

void glMapGrid1d(GLint un, GLdouble u1, GLdouble u2)
{
    (void)un;
    (void)u1;
    (void)u2;
}

void glMapGrid1f(GLint un, GLfloat u1, GLfloat u2)
{
    (void)un;
    (void)u1;
    (void)u2;
}

void glMapGrid2d(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2)
{
    (void)un;
    (void)u1;
    (void)u2;
    (void)vn;
    (void)v1;
    (void)v2;
}

void glMapGrid2f(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2)
{
    (void)un;
    (void)u1;
    (void)u2;
    (void)vn;
    (void)v1;
    (void)v2;
}

void glEvalPoint1(GLint i)
{
    (void)i;
}

void glEvalPoint2(GLint i, GLint j)
{
    (void)i;
    (void)j;
}

void glEvalMesh1(GLenum mode, GLint i1, GLint i2)
{
    (void)mode;
    (void)i1;
    (void)i2;
}

void glEvalMesh2(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2)
{
    (void)mode;
    (void)i1;
    (void)i2;
    (void)j1;
    (void)j2;
}

void glFogf(GLenum pname, GLfloat param)
{
    (void)pname;
    (void)param;
}

void glFogi(GLenum pname, GLint param)
{
    (void)pname;
    (void)param;
}

void glFogfv(GLenum pname, const GLfloat *params)
{
    (void)pname;
    (void)params;
}

void glFogiv(GLenum pname, const GLint *params)
{
    (void)pname;
    (void)params;
}

void glFeedbackBuffer(GLsizei size, GLenum type, GLfloat *buffer)
{
    (void)size;
    (void)type;
    (void)buffer;
}

void glPassThrough(GLfloat token)
{
    (void)token;
}

void glSelectBuffer(GLsizei size, GLuint *buffer)
{
    (void)size;
    (void)buffer;
}

void glInitNames(void)
{
}

void glLoadName(GLuint name)
{
    (void)name;
}

void glPushName(GLuint name)
{
    (void)name;
}

void glPopName(void)
{
}

void glDrawRangeElements(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices)
{
    (void)mode;
    (void)start;
    (void)end;
    (void)count;
    (void)type;
    (void)indices;
}

void glTexImage3D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
{
    (void)target;
    (void)level;
    (void)internalFormat;
    (void)width;
    (void)height;
    (void)depth;
    (void)border;
    (void)format;
    (void)type;
    (void)pixels;
}

void glTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels)
{
    (void)target;
    (void)level;
    (void)xoffset;
    (void)yoffset;
    (void)zoffset;
    (void)width;
    (void)height;
    (void)depth;
    (void)format;
    (void)type;
    (void)pixels;
}

void glCopyTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
    (void)target;
    (void)level;
    (void)xoffset;
    (void)yoffset;
    (void)zoffset;
    (void)x;
    (void)y;
    (void)width;
    (void)height;
}

void glColorTable(GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *table)
{
    (void)target;
    (void)internalformat;
    (void)width;
    (void)format;
    (void)type;
    (void)table;
}

void glColorSubTable(GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid *data)
{
    (void)target;
    (void)start;
    (void)count;
    (void)format;
    (void)type;
    (void)data;
}

void glColorTableParameteriv(GLenum target, GLenum pname, const GLint *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glColorTableParameterfv(GLenum target, GLenum pname, const GLfloat *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glCopyColorSubTable(GLenum target, GLsizei start, GLint x, GLint y, GLsizei width)
{
    (void)target;
    (void)start;
    (void)x;
    (void)y;
    (void)width;
}

void glCopyColorTable(GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
{
    (void)target;
    (void)internalformat;
    (void)x;
    (void)y;
    (void)width;
}

void glGetColorTable(GLenum target, GLenum format, GLenum type, GLvoid *table)
{
    (void)target;
    (void)format;
    (void)type;
    (void)table;
}

void glGetColorTableParameterfv(GLenum target, GLenum pname, GLfloat *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glGetColorTableParameteriv(GLenum target, GLenum pname, GLint *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glBlendEquation(GLenum mode)
{
    (void)mode;
}

void glBlendColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void glHistogram(GLenum target, GLsizei width, GLenum internalformat, GLboolean sink)
{
    (void)target;
    (void)width;
    (void)internalformat;
    (void)sink;
}

void glResetHistogram(GLenum target)
{
    (void)target;
}

void glGetHistogram(GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values)
{
    (void)target;
    (void)reset;
    (void)format;
    (void)type;
    (void)values;
}

void glGetHistogramParameterfv(GLenum target, GLenum pname, GLfloat *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glGetHistogramParameteriv(GLenum target, GLenum pname, GLint *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glMinmax(GLenum target, GLenum internalformat, GLboolean sink)
{
    (void)target;
    (void)internalformat;
    (void)sink;
}

void glResetMinmax(GLenum target)
{
    (void)target;
}

void glGetMinmax(GLenum target, GLboolean reset, GLenum format, GLenum types, GLvoid *values)
{
    (void)target;
    (void)reset;
    (void)format;
    (void)types;
    (void)values;
}

void glGetMinmaxParameterfv(GLenum target, GLenum pname, GLfloat *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glGetMinmaxParameteriv(GLenum target, GLenum pname, GLint *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glConvolutionFilter1D(GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *image)
{
    (void)target;
    (void)internalformat;
    (void)width;
    (void)format;
    (void)type;
    (void)image;
}

void glConvolutionFilter2D(GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *image)
{
    (void)target;
    (void)internalformat;
    (void)width;
    (void)height;
    (void)format;
    (void)type;
    (void)image;
}

void glConvolutionParameterf(GLenum target, GLenum pname, GLfloat params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glConvolutionParameterfv(GLenum target, GLenum pname, const GLfloat *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glConvolutionParameteri(GLenum target, GLenum pname, GLint params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glConvolutionParameteriv(GLenum target, GLenum pname, const GLint *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glCopyConvolutionFilter1D(GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
{
    (void)target;
    (void)internalformat;
    (void)x;
    (void)y;
    (void)width;
}

void glCopyConvolutionFilter2D(GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height)
{
    (void)target;
    (void)internalformat;
    (void)x;
    (void)y;
    (void)width;
    (void)height;
}

void glGetConvolutionFilter(GLenum target, GLenum format, GLenum type, GLvoid *image)
{
    (void)target;
    (void)format;
    (void)type;
    (void)image;
}

void glGetConvolutionParameterfv(GLenum target, GLenum pname, GLfloat *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glGetConvolutionParameteriv(GLenum target, GLenum pname, GLint *params)
{
    (void)target;
    (void)pname;
    (void)params;
}

void glSeparableFilter2D(GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *row, const GLvoid *column)
{
    (void)target;
    (void)internalformat;
    (void)width;
    (void)height;
    (void)format;
    (void)type;
    (void)row;
    (void)column;
}

void glGetSeparableFilter(GLenum target, GLenum format, GLenum type, GLvoid *row, GLvoid *column, GLvoid *span)
{
    (void)target;
    (void)format;
    (void)type;
    (void)row;
    (void)column;
    (void)span;
}

void glActiveTexture(GLenum texture)
{
    (void)texture;
}

void glClientActiveTexture(GLenum texture)
{
    (void)texture;
}

void glCompressedTexImage1D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid *data)
{
    (void)target;
    (void)level;
    (void)internalformat;
    (void)width;
    (void)border;
    (void)imageSize;
    (void)data;
}

void glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data)
{
    (void)target;
    (void)level;
    (void)internalformat;
    (void)width;
    (void)height;
    (void)border;
    (void)imageSize;
    (void)data;
}

void glCompressedTexImage3D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid *data)
{
    (void)target;
    (void)level;
    (void)internalformat;
    (void)width;
    (void)height;
    (void)depth;
    (void)border;
    (void)imageSize;
    (void)data;
}

void glCompressedTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid *data)
{
    (void)target;
    (void)level;
    (void)xoffset;
    (void)width;
    (void)format;
    (void)imageSize;
    (void)data;
}

void glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data)
{
    (void)target;
    (void)level;
    (void)xoffset;
    (void)yoffset;
    (void)width;
    (void)height;
    (void)format;
    (void)imageSize;
    (void)data;
}

void glCompressedTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
{
    (void)target;
    (void)level;
    (void)xoffset;
    (void)yoffset;
    (void)zoffset;
    (void)width;
    (void)height;
    (void)depth;
    (void)format;
    (void)imageSize;
    (void)data;
}

void glGetCompressedTexImage(GLenum target, GLint lod, GLvoid *img)
{
    (void)target;
    (void)lod;
    (void)img;
}

void glMultiTexCoord1d(GLenum target, GLdouble s)
{
    (void)target;
    (void)s;
}

void glMultiTexCoord1dv(GLenum target, const GLdouble *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord1f(GLenum target, GLfloat s)
{
    (void)target;
    (void)s;
}

void glMultiTexCoord1fv(GLenum target, const GLfloat *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord1i(GLenum target, GLint s)
{
    (void)target;
    (void)s;
}

void glMultiTexCoord1iv(GLenum target, const GLint *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord1s(GLenum target, GLshort s)
{
    (void)target;
    (void)s;
}

void glMultiTexCoord1sv(GLenum target, const GLshort *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord2d(GLenum target, GLdouble s, GLdouble t)
{
    (void)target;
    (void)s;
    (void)t;
}

void glMultiTexCoord2dv(GLenum target, const GLdouble *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord2f(GLenum target, GLfloat s, GLfloat t)
{
    (void)target;
    (void)s;
    (void)t;
}

void glMultiTexCoord2fv(GLenum target, const GLfloat *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord2i(GLenum target, GLint s, GLint t)
{
    (void)target;
    (void)s;
    (void)t;
}

void glMultiTexCoord2iv(GLenum target, const GLint *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord2s(GLenum target, GLshort s, GLshort t)
{
    (void)target;
    (void)s;
    (void)t;
}

void glMultiTexCoord2sv(GLenum target, const GLshort *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord3d(GLenum target, GLdouble s, GLdouble t, GLdouble r)
{
    (void)target;
    (void)s;
    (void)t;
    (void)r;
}

void glMultiTexCoord3dv(GLenum target, const GLdouble *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord3f(GLenum target, GLfloat s, GLfloat t, GLfloat r)
{
    (void)target;
    (void)s;
    (void)t;
    (void)r;
}

void glMultiTexCoord3fv(GLenum target, const GLfloat *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord3i(GLenum target, GLint s, GLint t, GLint r)
{
    (void)target;
    (void)s;
    (void)t;
    (void)r;
}

void glMultiTexCoord3iv(GLenum target, const GLint *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord3s(GLenum target, GLshort s, GLshort t, GLshort r)
{
    (void)target;
    (void)s;
    (void)t;
    (void)r;
}

void glMultiTexCoord3sv(GLenum target, const GLshort *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord4d(GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
{
    (void)target;
    (void)s;
    (void)t;
    (void)r;
    (void)q;
}

void glMultiTexCoord4dv(GLenum target, const GLdouble *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord4f(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
{
    (void)target;
    (void)s;
    (void)t;
    (void)r;
    (void)q;
}

void glMultiTexCoord4fv(GLenum target, const GLfloat *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord4i(GLenum target, GLint s, GLint t, GLint r, GLint q)
{
    (void)target;
    (void)s;
    (void)t;
    (void)r;
    (void)q;
}

void glMultiTexCoord4iv(GLenum target, const GLint *v)
{
    (void)target;
    (void)v;
}

void glMultiTexCoord4s(GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
{
    (void)target;
    (void)s;
    (void)t;
    (void)r;
    (void)q;
}

void glMultiTexCoord4sv(GLenum target, const GLshort *v)
{
    (void)target;
    (void)v;
}

void glLoadTransposeMatrixd(const GLdouble m[16])
{
    (void)m;
}

void glLoadTransposeMatrixf(const GLfloat m[16])
{
    (void)m;
}

void glMultTransposeMatrixd(const GLdouble m[16])
{
    (void)m;
}

void glMultTransposeMatrixf(const GLfloat m[16])
{
    (void)m;
}

void glSampleCoverage(GLclampf value, GLboolean invert)
{
    (void)value;
    (void)invert;
}

}  /* extern "C" */
