{% set name = "coin3d-rt" %}
{% set sha256_superglue = "1ff45bb0fa703eee730b51911acb0d14c46ba66adce01be5167b14694e123018" %}

package:
    name: {{ name }}
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'failed') }}

source:
    - git_url : ../../

    - url: https://github.com/realthunder/superglu/archive/refs/tags/v1.3.1-conda.tar.gz
      sha256: 1ff45bb0fa703eee730b51911acb0d14c46ba66adce01be5167b14694e123018
      folder: superglu

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
    build:
        - {{ compiler('cxx') }}
        # - {{ stdlib("c") }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libXxf86vm') }}  # [linux]
        - {{ cdt('libxi-devel') }} # [linux]
        - {{ cdt('libxext') }}     # [linux]
        - cmake 3.18.*
        - ninja
    host:
        - boost-cpp
        - libglu  # [linux]
        - xorg-xproto   # [linux]
        - expat
    run:
        - libglu  # [linux]
        - expat

# test:
#     requires:
#         - {{ cdt('mesa-libgl-devel') }}  # [linux]
#         - {{ compiler('c') }}
#         - {{ compiler('cxx') }}
#     files:
#         - test.cpp  # [linux]
#     commands:
#         - ${CXX} -o test test.cpp -Wl,-rpath-link -lCoin -L${PREFIX}/lib/ -I${PREFIX}/include/  # [linux]
#         - ./test  # [linux]
#         - where /r "%PREFIX%"  Coin4.dll  # [win]
#         - test -f ${PREFIX}/lib/libCoin.dylib  # [osx]

about:
    home: https://github.com/realthunder/coin
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: Coin3D with improved shadow renderering
    description: Coind3D with improved support of shadow rendering 

extra:
    recipe-maintainers:
        - realthunder
