{% set name = "soqt-rt" %}
{% set version = "1.6.0" %}
{% set sha256 = "ee3d2a9a81c0d83d43b39b27ec353ef262ad2969521ac142b88f828095cc8757" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/realthunder/soqt/releases/download/SoQt-{{ version }}-conda/soqt-{{ version }}-src.tar.gz
    sha256: {{ sha256 }}
    patches:
      - gl_private_linking.patch  # [linux]


build:
    number: 3

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
        - ninja
        - cmake
        - qt-main # [build_platform != target_platform]
    host:
        - qt-main        # [not win]
        - qt-main 5.15.4 # [win]
        - coin3d-rt
        
    run:
        - qt-main        # [not win]
        - qt-main 5.15.4 # [win]
        - coin3d-rt

# test:
#     requires:
#         - cmake
#         - ninja
#         - {{ compiler("cxx") }}
#         - {{ cdt('mesa-libgl-devel') }}  # [linux]
#         - {{ cdt('mesa-dri-drivers') }}  # [linux]
#         - {{ cdt('libselinux') }}  # [linux]
#         - {{ cdt('libxdamage') }}  # [linux]
#         - {{ cdt('libxxf86vm') }}  # [linux]
#         - {{ cdt('libxext') }}     # [linux]
#
#     files:
#         - CMakeLists.txt
#
#     commands:
#         - cmake -G "Ninja" .

about:
    home: https://github.com/realthunder/coin
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING
    summary: SoQt library for Coin3D with enhanced shadow rendering.
    description: SoQt is a Qt GUI component toolkit library for Coin.  It is also compatible
                 with SGI and TGS Open Inventor, and the API is based on the API of the
                 InventorXt GUI component toolkit.

extra:
    recipe-maintainers:
        - realthunder
