name: Publish pivy

on:
  push:
    tags:
      - "*pivy"

  workflow_dispatch:

jobs:
  conda_deployment_with_new_tag:
    strategy:
      # fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.11"]
        arch : ["64"]
        include:
          - os: windows-latest
            python-version: "3.8"
            arch : "64"
          - os: ubuntu-latest
            arch: aarch64
            python-version: "3.11"
          - os: macos-latest
            arch: arm64
            python-version: "3.11"
    uses: ./.github/workflows/builder.yml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      python-version: ${{ matrix.python-version }}
      recipe: conda/02-pivy
      use_mamba: false
    secrets:
      token: ${{ secrets.ANACONDA_TOKEN }}
